### ISSUE TITLE
Can you publish the pretrained net?

### ISSUE THREAD

**Issue by yakirsudry** [yuzhuoren/IndoorLayout#1]

**Comment by yuzhuoren** [comment]
@yakirsudry As written in README: The weight initialization can be downloaded here:https://gist.github.com/longjon/16db1e4ad3afc2614067. The trained model can be download here:https://www.dropbox.com/s/tyrbuafu7ejcq80/train_iter_454400.caffemodel?dl=0.

Please let me know if you have any problem download the model.
